# Site settings
title: PREDICT Pain Lab at MCW
email: jmischka@mcw.edu
description: This site is a work in progress.
baseurl: ""
copyright_holder: PREDICT Pain Lab at MCW
copyright_year: 2016
author: http://www.mcw.edu/Anesthesiology.htm
url: "http://www.predictpainlab.org"
# twitter_username: jekyllrb
# github_username:  jekyll

paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
permalink: pretty
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - webpack.config.js
  - gulpfile.js
  - rollup.config.js
  - todo.txt
gems:
  - jekyll-paginate
  - jekyll-autoprefixer

collections:
  - sections
  - milwaukee_attractions
  - people

prose:
  rooturl: "_posts"
  siteurl: "http://www.predictpainlab.org"
  media: "resources/posts"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: ""
      type: "sections"
    values:
      layout: "section"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

autoprefixer:
  only_production: true
